apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: smarfarm
      defaultBucket: soil_data
      tlsSkipVerify: true
    secureJsonData:
      token: smarfarm-token-2026
